# Generated by Django 4.2.3 on 2023-07-23 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('JO', 'Joy'), ('PE', 'Peace'), ('SA', 'Satisfaction'), ('HO', 'Hope'), ('CO', 'Courage'), ('BO', 'Boredom'), ('FR', 'Frustration'), ('AN', 'Anxiety'), ('SA', 'Sadness'), ('AN', 'Anger'), ('FE', 'Fear'), ('DE', 'Despair')], max_length=2)),
                ('intensity', models.CharField(choices=[('1', 'Barely'), ('2', 'Mildly'), ('3', 'Moderately'), ('4', 'Very'), ('5', 'Extremely')], max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
