# Generated by Django 4.2.3 on 2023-07-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='emotion',
            field=models.CharField(choices=[('JO', 'Joy'), ('PE', 'Peace'), ('ST', 'Satisfaction'), ('HO', 'Hope'), ('CO', 'Courage'), ('BO', 'Boredom'), ('FR', 'Frustration'), ('AN', 'Anxiety'), ('SA', 'Sadness'), ('AN', 'Anger'), ('FE', 'Fear'), ('DE', 'Despair')], max_length=2),
        ),
    ]
